storage_account_name="aoaiuatstgtfstatetqi"
resource_group_name="aoaiuat-rg-launchpad"
vnet_id="/subscriptions/e22a351f-db36-4a02-9793-0f2189d5f3ab/resourceGroups/gcci-platform/providers/Microsoft.Network/virtualNetworks/gcci-vnet-project"
subnet_id="/subscriptions/e22a351f-db36-4a02-9793-0f2189d5f3ab/resourceGroups/gcci-platform/providers/Microsoft.Network/virtualNetworks/gcci-vnet-project/subnets/ServiceSubnet"
log_analytics_workspace_id="/subscriptions/e22a351f-db36-4a02-9793-0f2189d5f3ab/resourceGroups/gcci-agency-law/providers/Microsoft.OperationalInsights/workspaces/gcci-agency-workspace"
prefix="aoaiuat"
environment="sandpit"
